sudo: false

language: c

addons:
  apt:
    packages:
    - libgmp-dev

env:
- ARGS=""
- ARGS="--resolver lts"
- ARGS="--resolver nightly"

matrix:
  allow_failures:
    - env: ARGS="--resolver lts"
    - env: ARGS="--resolver nightly"
  fast_finish: true

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- travis_retry stack install stylish-haskell
- travis_retry stack install hlint

script:
- stack $ARGS --no-terminal --install-ghc test --haddock
- hlint .
- stylish-haskell -i -- **/*.hs && git diff --exit-code

cache:
  directories:
  - $HOME/.stack
